State:9
Info:正式版 1.16.5, Fabric 0.19.2
Logo:pack://application:,,,/Plain Craft Launcher 2;component/Images/Blocks/Fabric.png
ReleaseTime:2021-01-15 00:05
VersionFabric:0.19.2
VersionOptiFine:
VersionLiteLoader:False
VersionForge:
VersionNeoForge:
VersionVanillaName:1.16.5
VersionVanilla:16.0.5
VersionArgumentIndieV2:True
