State:9
Info:正式版 1.20.6, Fabric 0.19.2
Logo:pack://application:,,,/Plain Craft Launcher 2;component/Images/Blocks/Fabric.png
ReleaseTime:2024-04-29 20:40
VersionFabric:0.19.2
VersionOptiFine:
VersionLiteLoader:False
VersionForge:
VersionNeoForge:
VersionVanillaName:1.20.6
VersionVanilla:20.0.6
VersionArgumentIndieV2:True
