State:1
Info:正式版 1.8.9
Logo:pack://application:,,,/Plain Craft Launcher 2;component/Images/Blocks/Grass.png
ReleaseTime:2015-12-03 17:24
VersionFabric:
VersionOptiFine:
VersionLiteLoader:False
VersionForge:
VersionNeoForge:
VersionVanillaName:1.8.9
VersionVanilla:8.0.9
VersionArgumentIndieV2:True
