State:4
Info:正式版 1.20.6, OptiFine J1 pre18
Logo:pack://application:,,,/Plain Craft Launcher 2;component/Images/Blocks/GrassPath.png
ReleaseTime:2024-04-29 20:40
VersionFabric:
VersionOptiFine:J1_pre18
VersionLiteLoader:False
VersionForge:
VersionNeoForge:
VersionVanillaName:1.20.6
VersionVanilla:20.0.6
