State:1
Info:正式版 1.12.2
Logo:pack://application:,,,/Plain Craft Launcher 2;component/Images/Blocks/Grass.png
ReleaseTime:2017-09-18 16:39
VersionFabric:
VersionOptiFine:
VersionLiteLoader:False
VersionForge:
VersionNeoForge:
VersionVanillaName:1.12.2
VersionVanilla:12.0.2
VersionArgumentIndieV2:True
