State:6
Info:正式版 1.8.9, Forge 11.15.1.1902, LiteLoader
Logo:pack://application:,,,/Plain Craft Launcher 2;component/Images/Blocks/Anvil.png
ReleaseTime:2015-12-03 17:24
VersionFabric:
VersionOptiFine:
VersionLiteLoader:True
VersionForge:11.15.1.1902
VersionNeoForge:
VersionVanillaName:1.8.9
VersionVanilla:8.0.9
