State:7
Info:正式版 1.20.6, NeoForge 20.6.139
Logo:pack://application:,,,/Plain Craft Launcher 2;component/Images/Blocks/NeoForge.png
ReleaseTime:2024-04-29 20:40
VersionFabric:
VersionOptiFine:
VersionLiteLoader:False
VersionForge:
VersionNeoForge:20.6.139
VersionVanillaName:1.20.6
VersionVanilla:20.0.6
VersionArgumentIndieV2:True
