State:4
Info:正式版 1.19.1, OptiFine H9
Logo:pack://application:,,,/Plain Craft Launcher 2;component/Images/Blocks/GrassPath.png
ReleaseTime:2022-07-27 17:25
VersionFabric:
VersionOptiFine:H9
VersionLiteLoader:False
VersionForge:
VersionNeoForge:
VersionVanillaName:1.19.1
VersionVanilla:19.0.1
VersionArgumentIndieV2:True
