State:4
Info:正式版 1.18.1, OptiFine H6
Logo:pack://application:,,,/Plain Craft Launcher 2;component/Images/Blocks/GrassPath.png
ReleaseTime:2021-12-10 16:23
VersionFabric:
VersionOptiFine:H6
VersionLiteLoader:False
VersionForge:
VersionNeoForge:
VersionVanillaName:1.18.1
VersionVanilla:18.0.1
