State:8
Info:正式版 1.12.2, LiteLoader
Logo:pack://application:,,,/Plain Craft Launcher 2;component/Images/Blocks/Egg.png
ReleaseTime:2017-09-18 16:39
VersionFabric:
VersionOptiFine:
VersionLiteLoader:True
VersionForge:
VersionNeoForge:
VersionVanillaName:1.12.2
VersionVanilla:12.0.2
VersionArgumentIndieV2:True
