State:8
Info:正式版 1.8.9, LiteLoader
Logo:pack://application:,,,/Plain Craft Launcher 2;component/Images/Blocks/Egg.png
ReleaseTime:2015-12-03 17:24
VersionFabric:
VersionOptiFine:
VersionLiteLoader:True
VersionForge:
VersionNeoForge:
VersionVanillaName:1.8.9
VersionVanilla:8.0.9
VersionArgumentIndieV2:True
