State:6
Info:正式版 26.1, Forge 62.0.9
Logo:pack://application:,,,/Plain Craft Launcher 2;component/Images/Blocks/Anvil.png
ReleaseTime:2026-03-24 20:11
VersionFabric:
VersionOptiFine:
VersionLiteLoader:False
VersionForge:62.0.9
VersionNeoForge:
VersionVanillaName:26.1
VersionVanilla:26.1.0
VersionArgumentIndieV2:True
