State:9
Info:正式版 1.19.1, Fabric 0.19.2
Logo:pack://application:,,,/Plain Craft Launcher 2;component/Images/Blocks/Fabric.png
ReleaseTime:2022-07-27 17:25
VersionFabric:0.19.2
VersionOptiFine:
VersionLiteLoader:False
VersionForge:
VersionNeoForge:
VersionVanillaName:1.19.1
VersionVanilla:19.0.1
VersionArgumentIndieV2:True
