State:6
Info:正式版 1.12.2, Forge 14.23.5.2847
Logo:pack://application:,,,/Plain Craft Launcher 2;component/Images/Blocks/Anvil.png
ReleaseTime:2017-09-18 16:39
VersionFabric:
VersionOptiFine:
VersionLiteLoader:False
VersionForge:14.23.5.2847
VersionNeoForge:
VersionVanillaName:1.12.2
VersionVanilla:12.0.2
