State:9
Info:正式版 1.17.1, Fabric 0.19.2
Logo:pack://application:,,,/Plain Craft Launcher 2;component/Images/Blocks/Fabric.png
ReleaseTime:2021-07-06 20:01
VersionFabric:0.19.2
VersionOptiFine:
VersionLiteLoader:False
VersionForge:
VersionNeoForge:
VersionVanillaName:1.17.1
VersionVanilla:17.0.1
VersionArgumentIndieV2:True
