State:1
Info:正式版 1.18.1
Logo:pack://application:,,,/Plain Craft Launcher 2;component/Images/Blocks/Grass.png
ReleaseTime:2021-12-10 16:23
VersionFabric:
VersionOptiFine:
VersionLiteLoader:False
VersionForge:
VersionNeoForge:
VersionVanillaName:1.18.1
VersionVanilla:18.0.1
VersionArgumentIndieV2:True
