State:6
Info:正式版 1.17.1, Forge 37.0.103
Logo:pack://application:,,,/Plain Craft Launcher 2;component/Images/Blocks/Anvil.png
ReleaseTime:2021-07-06 20:01
VersionFabric:
VersionOptiFine:
VersionLiteLoader:False
VersionForge:37.0.103
VersionNeoForge:
VersionVanillaName:1.17.1
VersionVanilla:17.0.1
VersionArgumentIndieV2:True
