State:1
Info:正式版 1.17.1
Logo:pack://application:,,,/Plain Craft Launcher 2;component/Images/Blocks/Grass.png
ReleaseTime:2021-07-06 20:01
VersionFabric:
VersionOptiFine:
VersionLiteLoader:False
VersionForge:
VersionNeoForge:
VersionVanillaName:1.17.1
VersionVanilla:17.0.1
VersionArgumentIndieV2:True
